module.exports = {
  DRAFT: 'DRAFT',
  CONFIRMED: 'CONFIRMED',
  PLANNING: 'PLANNING',
  PLANNED: 'PLANNED',
  DEFERRED: 'DEFERRED',
  LOADING: 'LOADING',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  ISSUE_REPORTED: 'ISSUE_REPORTED',
  CLOSED: 'CLOSED',
};
