module.exports = {
  PLANNED: 'PLANNED',
  READY_FOR_LOADING: 'READY_FOR_LOADING',
  LOADING: 'LOADING',
  READY: 'READY',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  INTERRUPTED: 'INTERRUPTED',
};
